merge - version fixed Authentication endpoint
alkemyTech/OT140-SERVER pull request #105
Opened 2022-03-26 14:50 UTC by Seba-Rigeiro

2022-04-08 15:22 UTC, maxxCeballos requested changes

2022-04-08 15:22 UTC, maxxCeballos commented on middlewares/validations.js
> +<<<<<<< HEAD
Seba aca te estan quedando lineas de un re conflicto de merge

2022-04-08 15:22 UTC, maxxCeballos commented on middlewares/validations.js
> +=======
Lo mismo aca

2022-04-08 15:22 UTC, maxxCeballos commented on middlewares/validations.js
> +>>>>>>> 575873d1b6f8d169557b9b484441c05183438ce3
Lo mismo aca

2022-04-10 22:10 UTC, Seba-Rigeiro commented on middlewares/validations.js
> +<<<<<<< HEAD
Listo Maxi, solucionado

2022-04-10 22:10 UTC, Seba-Rigeiro commented on middlewares/validations.js
> +=======
solucionado

2022-04-11 01:23 UTC, merged