news model: set soft delete
alkemyTech/OT140-SERVER pull request #107
Opened 2022-04-04 11:42 UTC by raccaricardo

- Set soft delete:

![new model img](https://user-images.githubusercontent.com/22423926/161536319-eb4f6936-1de0-4a2f-b290-e60ca1e18d49.png)

2022-04-04 17:38 UTC, maxxCeballos requested changes

2022-04-04 17:38 UTC, maxxCeballos commented on models/new.js
> +    paranoid: true
Ricardo, en la linea 13 donde se hace la asociacion. En lugar de models.Role no es models.Categories ?

2022-04-05 19:30 UTC, raccaricardo commented
Hola Maxi, ahí hice la corrección

2022-04-08 15:14 UTC, maxxCeballos approved these changes

2022-04-08 15:14 UTC, merged