50 news endpoint delete
alkemyTech/OT140-SERVER pull request #108
Opened 2022-04-04 17:04 UTC by raccaricardo

Parte 2 de pull request que habia enviado anteriormente.
Affected Files: 

- controllers/news.js
- routes/news.js

![deleteNewController](https://user-images.githubusercontent.com/22423926/161595003-98f45650-4149-46b3-a466-fcbc4d17e7f9.png)

2022-04-04 17:52 UTC, maxxCeballos requested changes

2022-04-04 17:52 UTC, maxxCeballos commented on controllers/news.js
> +      if( isNaN(id) || !req.params.id ) return res.status(400).json("id number is required or is not a number");
La validacion isNaN o se puede hacer como middleware en un validator, o dejarla que ingrese a la consulta y falle por no encontrar tal id.
La validacion de que no exista el param id es inncesaria ya que esta definido en la ruta y tiene que existir para poder ingresar por la ruta esperada.

2022-04-04 17:52 UTC, maxxCeballos commented on controllers/news.js
> +      await New.destroy({where: { id: parseInt(id) }});
Con una sola consulta a la base de datos se puede implementar la misma logica, no es necesario realizar dos consultas.

2022-04-04 17:52 UTC, maxxCeballos commented on validator/news.js
>    check("content").exists().not().isEmpty(),
Fuera del alcance del ticket.

2022-04-04 17:52 UTC, maxxCeballos commented on routes/news.js
> +    .delete("/:id", deleteNew)
un usuario administrador puede ejecutar esta operacion, por lo tanto se deberia agregar middleware de check de Rol.

2022-04-07 12:30 UTC, raccaricardo commented
- Agregué middleware de role
- y borrè los cambios que hice en validator/news.js

2022-04-08 15:10 UTC, maxxCeballos requested changes

2022-04-08 15:10 UTC, maxxCeballos commented on routes/news.js
> +    .delete("/:id", deleteNew)
Ricardo, muchisimo mejor! Falta agregar el middleware a la ruta para que sea validado que el usuario sea Administrador. Quedaria algo como  `router.delete(path, middleware, controller)`

2022-04-11 20:25 UTC, maxxCeballos approved these changes

2022-04-11 20:28 UTC, merged