list-slides
alkemyTech/OT140-SERVER pull request #116
Opened 2022-04-08 09:26 UTC by pyvan23

2022-04-08 14:38 UTC, maxxCeballos requested changes

2022-04-08 14:38 UTC, maxxCeballos commented on routes/slides.js
> +router.get("/", listSlide);
Un usuario administrador puede realizar esta accion. Agreggar middleware de validacion de Rol. Esta hecho en middleware/commons.js

2022-04-08 14:38 UTC, maxxCeballos commented on controllers/slidesController.js
> +    res.status(404).json({
Si se lanza un error no es porque no encontro un recurso, que es lo que marca el 404. En caso de no encontrar nada devolverias una lista vacia.
En este caso de error el status code apropiado seria un 500.

2022-04-08 14:38 UTC, maxxCeballos commented on controllers/slidesController.js
> +    res.status(201).json({
201 se utiliza cuando se crea un recurso.
En este caso seria un 200, que especifica que la transaccion se ejecuto ok.

2022-04-08 14:41 UTC, pyvan23 commented
Bueno,perfecto

El vie., 8 de abr. de 2022 11:38, maxxCeballos ***@***.***>
escribió:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In routes/slides.js
> <https://github.com/alkemyTech/OT140-SERVER/pull/116#discussion_r846176637>
> :
>
> >
>  const router = Router();
>  /* GET home page. */
>
> -router.post('/', postSlide );
> -router.put('/:id', updateSlide );
> +router.post("/", postSlide);
> +router.put("/:id", updateSlide);
> +router.get("/", listSlide);
>
> Un usuario administrador puede realizar esta accion. Agreggar middleware
> de validacion de Rol. Esta hecho en middleware/commons.js
> ------------------------------
>
> In controllers/slidesController.js
> <https://github.com/alkemyTech/OT140-SERVER/pull/116#discussion_r846178198>
> :
>
> > +
> +    res.status(201).json({
> +      msg: "Slide Updated",
> +      updatedSlide: updatedSlide,
> +    });
> +  }
> +};
> +const listSlide = async (req, res) => {
> +  try {
> +    const list = await Slide.findAll({ attributes: ["imageUrl", "order"] });
> +    res.status(201).json({
> +      msg: "List of Images",
> +      list,
> +    });
> +  } catch (error) {
> +    res.status(404).json({
>
> Si se lanza un error no es porque no encontro un recurso, que es lo que
> marca el 404. En caso de no encontrar nada devolverias una lista vacia.
> En este caso de error el status code apropiado seria un 500.
> ------------------------------
>
> In controllers/slidesController.js
> <https://github.com/alkemyTech/OT140-SERVER/pull/116#discussion_r846179214>
> :
>
> > +      },
> +      { where: { id } }
> +    );
> +
> +    const updatedSlide = await Slide.findByPk(id);
> +
> +    res.status(201).json({
> +      msg: "Slide Updated",
> +      updatedSlide: updatedSlide,
> +    });
> +  }
> +};
> +const listSlide = async (req, res) => {
> +  try {
> +    const list = await Slide.findAll({ attributes: ["imageUrl", "order"] });
> +    res.status(201).json({
>
> 201 se utiliza cuando se crea un recurso.
> En este caso seria un 200, que especifica que la transaccion se ejecuto ok.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alkemyTech/OT140-SERVER/pull/116#pullrequestreview-936538972>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUPOZSQNWWBN4DHK2M3TF5LVEBAHVANCNFSM5S36WH7Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-12 10:22 UTC, pyvan23 commented
saque punto y coma de routes/news de mas,comente lineas en routes/members.js y agregue middleware para chequear el rol

2022-04-16 20:02 UTC, pyvan23 commented
listado de slides funcionando,con chequeo de rol

2022-04-18 19:33 UTC, maxxCeballos requested changes

2022-04-18 19:33 UTC, maxxCeballos commented on controllers/authController.js
> +                    res.status(200).json({ user: user,token })
Este cambio no se corresponde con el ticket

2022-04-18 19:33 UTC, maxxCeballos commented on routes/members.js
> +router.get('/', getAll);*/
Evitar cambios que no se corresponden con el ticket

2022-04-18 23:42 UTC, pyvan23 commented
Hice las modificaciones que me corregiste Maxi,y mergee con main asi que ya no toque el routes/members,no hay conflicto ahora

2022-04-20 20:15 UTC, maxxCeballos approved these changes

2022-04-20 20:16 UTC, merged