delete-slide
alkemyTech/OT140-SERVER pull request #117
Opened 2022-04-08 10:00 UTC by pyvan23

2022-04-08 14:34 UTC, maxxCeballos requested changes

2022-04-08 14:34 UTC, maxxCeballos commented on routes/slides.js
> +router.delete('/:id',deleteSlide)
Un usuario administrador es quien puede realizar esta accion, hay que agregar middleware para chequear el rol. Ya esta inmplementado en middlewares/commons.js

2022-04-08 14:36 UTC, pyvan23 commented
Ok,maxi

El vie., 8 de abr. de 2022 11:34, maxxCeballos ***@***.***>
escribió:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In routes/slides.js
> <https://github.com/alkemyTech/OT140-SERVER/pull/117#discussion_r846174851>
> :
>
> >
>  const router = Router();
>  /* GET home page. */
>
>  router.post('/', postSlide );
>  router.put('/:id', updateSlide );
> +router.delete('/:id',deleteSlide)
>
> Un usuario administrador es quien puede realizar esta accion, hay que
> agregar middleware para chequear el rol. Ya esta inmplementado en
> middlewares/commons.js
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alkemyTech/OT140-SERVER/pull/117#pullrequestreview-936536280>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUPOZSTJHHLQNYM2INSHLO3VEA7W7ANCNFSM5S4BPTAQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-16 21:53 UTC, pyvan23 commented
cambie una linea en el modelo de slides por que no me lo encontraba por pk,y agregue checktoken y checkeo de rol administrador para eliminar

2022-04-18 19:21 UTC, maxxCeballos requested changes

2022-04-18 19:21 UTC, maxxCeballos commented on controllers/slidesController.js
> +  }
si sucede un error no se esta handleando, para estoy hay que envolver el cuerpo en un try/catch

2022-04-18 19:21 UTC, maxxCeballos commented on controllers/authController.js
> +                        res.status(200).json({ user: user,token })
Esto esta fuera del alcance del ticket. Si hay que hacer arreglos abrir un branch aparte haciendo una descripcion de lo que se quiere fixear.

2022-04-20 20:19 UTC, maxxCeballos approved these changes

2022-04-20 20:22 UTC, merged