Middleware ownership was added OT140-34
alkemyTech/OT140-SERVER pull request #136
Opened 2022-04-25 01:56 UTC by alesandroo92

Se agrega el middleware ownership

![1](https://user-images.githubusercontent.com/91065194/165008269-ce65c773-58ac-4829-b390-de4fa0a2096e.jpg)

![2](https://user-images.githubusercontent.com/91065194/165008274-0e98db26-632a-469e-bbdb-d244e1e65dc8.jpg)

2022-04-26 03:49 UTC, maxxCeballos requested changes

2022-04-26 03:49 UTC, maxxCeballos commented on middlewares/ownership.js
> +    }
Ale fijate que esta funcion es igual a la primera, solo agregas en el if la validacion de `RoleId !== 1`.
Podrias poner todo en una funcion y llamarla de manera que represente lo que esta validando, por ejemplo isOwnership si es true, entonces next() sino res(403)

2022-04-26 11:34 UTC, alesandroo92 commented on middlewares/ownership.js
> +    }
Corregido en el commit "ownership was modified"

2022-04-27 03:35 UTC, maxxCeballos approved these changes

2022-04-27 03:35 UTC, merged