86 paginated news
alkemyTech/OT140-SERVER pull request #88
Opened 2022-03-14 07:05 UTC by raccaricardo

- News pagination : with previousPage and nextPage 
- Endpoint news added: **/list**   
- Request Query: **from = 0** and **limit = 0**

![paginated-news-controller](https://user-images.githubusercontent.com/22423926/158120906-b7db6226-7e8e-4b66-9007-8f4e3d7fe834.png)

![paginated-response-news](https://user-images.githubusercontent.com/22423926/158120918-271ed841-6aec-42c2-a6ab-e7cbc81dba03.png)

2022-04-04 00:10 UTC, maxxCeballos requested changes

2022-04-04 00:10 UTC, maxxCeballos commented on controllers/news.js
> +      news
- Poner toda la logica de paginado en una funcion aparte. Tiene que ser reutilziable para otras entidades tambien. En Categories existe un paginado, se esta repitiendo la misma logica en cada servicio que se quiera paginar.  Hablar con Artemio en caso de necesitar ayuda para mover la logica del paginado de categories a la nueva funcion que implementes.
- Se estan haciendo dos consultas a la bd, con una sola alcanza para lograr la salida esperada.
- No dejar console.log() en produccion.
- El nombre de la funcion no deberia incluir paginated, eso es una caracteristica que se añade para ganar performance, pero no tiene que ver con el proposito de la funcion que es listar Novedades.

2022-04-10 03:15 UTC, raccaricardo commented
- He creado la funcion reutilizable /helpers/db/listItemsDB
- Agregué la función en controladores de categories y news.

2022-04-10 20:01 UTC, raccaricardo commented
Resolvi conflictos para hacer el pr.
- Se agregó funcion para listar objetos de la db: helpers/db/listItemsDB.js

-Controllers: 
- categories.controller 
   - renombrado a categories
   - se implementó la funcion para listar desde la db
- members 
   - se implementó la funcion para listar desde la db
- news
   - se implementó la funcion para listar desde la db
   -  se borarron console.log
   
- Routes 
- categories: se corrigió importacion(por cambio de nombre de archivo categories.controller
- news: se agregó endpoint para listar News y se eliminó comentario inncesario

2022-04-11 20:19 UTC, maxxCeballos approved these changes

2022-04-11 20:19 UTC, merged