Organization-data-correction-OT140-23
alkemyTech/OT140-SERVER pull request #89
Opened 2022-03-14 09:54 UTC by javier1793-op

**Branch update to the latest version of main**

### **test run**

![image](https://user-images.githubusercontent.com/67015301/158148307-242b72ae-0f05-48be-977a-3ea084026bba.png)

### **test results**

![image](https://user-images.githubusercontent.com/67015301/158148431-9af48597-9119-4c4d-a47c-e2ce167650fc.png)

2022-04-04 00:20 UTC, maxxCeballos requested changes

2022-04-04 00:20 UTC, maxxCeballos commented on seeders/20220305223343-create-organizate.js
> +};
Esto esta fuera del alcance del ticket 23.

2022-04-04 00:20 UTC, maxxCeballos commented on models/testimonial.js
> -    timestamps: true,
por que se elimina el timestamp? de todos modos esto esta fuera del alcance del ticket 23.

2022-04-04 00:20 UTC, maxxCeballos commented on controllers/organization.js
> +        const orga = await Organization.findAll({
utilizar nombres de variables mas apropiados, orga no me dice nada descriptivo.

2022-04-04 00:20 UTC, maxxCeballos commented on controllers/organization.js
> +        res.json({ msg: 'there are no organizations to display' });
Si ocurre un error en este caso no es porque no haya organizaciones para mostrar, puede ser por un error de conexion en la base de datos por ejemplo.

2022-04-05 02:19 UTC, javier1793-op commented
Agrado las correcciones para su revisión

2022-04-08 15:51 UTC, maxxCeballos approved these changes

2022-04-08 15:54 UTC, merged