Contact-list-correction-OT140-65
alkemyTech/OT140-SERVER pull request #90
Opened 2022-03-14 10:13 UTC by javier1793-op

### **Update contact-list branch with main**

### **test run**

![image](https://user-images.githubusercontent.com/67015301/158151620-8390522b-0ffe-4f1b-a59b-d8375b1be022.png)

### **test results**

![image](https://user-images.githubusercontent.com/67015301/158151754-3cdfb577-5e87-46d2-a68e-0abe793ef86b.png)

2022-04-04 00:57 UTC, maxxCeballos requested changes

2022-04-04 00:57 UTC, maxxCeballos commented on migrations/20220301032227-contacts.js
> +
fuera del alcance del ticket 65

2022-04-04 00:57 UTC, maxxCeballos commented on models/testimonial.js
> +    paranoid: true
por que se saca timestamp? fuera del alcance del ticket 65

2022-04-04 00:57 UTC, maxxCeballos commented on seeders/20220305012944-contacts.js
> +};
Esto esta fuera del alcance del ticket 65

2022-04-04 00:57 UTC, maxxCeballos commented on controllers/contacts.js
> +        res.json({ msg: 'No contact list to display' });
El error en este caso no es por no encontrar contactos sino por otro motivo, por ejemplo error de conexion con la base de datos. Validar el caso de no encontrar contactos a mostrar dentro del try.

2022-04-04 00:57 UTC, maxxCeballos commented on app.js
> +app.use('/backoffice', contactsRouter);
utilizar el router de contacts ya implementado. En lugar de quedar /backoffice/contacts va a quedar contacts/backoffice.

2022-04-04 00:57 UTC, maxxCeballos commented on routes/contacts.js
> +router.get('/contacts', getContacts);
Un usuario administrador puede acceder al endpoint, por lo tanto se debe aplicar el middleware de check de rol.

2022-04-05 02:50 UTC, javier1793-op commented
agregado correcciones para su revisión

2022-04-08 15:49 UTC, maxxCeballos requested changes

2022-04-08 15:49 UTC, maxxCeballos commented on routes/contacts.js
> +    router.get('/backoffice', checkToken, getContacts);
No hay que validar solo que viaje el token, sino que el usuario que viaja en el token tenga permiso de Admin. Esto esta implementado en middlwares/commons.js

2022-04-18 19:29 UTC, merged