Ot140 91 (BRANCH)
alkemyTech/OT140-SERVER pull request #93
Opened 2022-03-15 04:54 UTC by ezequielrango

**Agregar documentación a Novedades**

COMO desarrollador
QUIERO disponer de una documentación de los endpoints de Novedades
PARA tener referencias de su funcionamiento

**LINK DOCUMENTACIÓN:**

https://documenter.getpostman.com/view/17593482/UVsLQRL3

**Solucionado problema de categoriesId** 

![errorDemostration](https://user-images.githubusercontent.com/79542271/158308297-2651ac33-4b6b-4ece-9782-3da3688daca2.JPG)

Si eliminaba la línea 13 del archivo funcionaba : 

![problemaRelacionVS](https://user-images.githubusercontent.com/79542271/158308798-36f5c69f-f2b8-4dff-bbda-9ae069718604.JPG)

![problemaRelacionConsola](https://user-images.githubusercontent.com/79542271/158308691-12c46c89-4fe5-442c-98d4-a8c9989db095.JPG)

**RESOLUCIÓN CONFLICTO**

CÓDIGO :

![solucion](https://user-images.githubusercontent.com/79542271/158308917-b0618dc4-f442-486a-8af5-af5cf1e7a2df.JPG)

CONSOLA Y POSTMAN: 

![EXAMPLEEEE](https://user-images.githubusercontent.com/79542271/158308977-50d676eb-7944-444a-acff-415c0283d00b.JPG)

2022-04-04 01:16 UTC, maxxCeballos requested changes

2022-04-04 01:16 UTC, maxxCeballos commented on documentation/news.txt
> +https://documenter.getpostman.com/view/17593482/UVsLQRL3
Los endpoints de news estan restringidos a usuarios admin. 
Falta detallar en cada request el token a validar.
Que pasa si la respuesta no es success? se pueden documentar las respuestas de error? Por ejemplo por error de autorizacion o internal server?

2022-04-04 01:16 UTC, maxxCeballos commented on models/categories.js
> +            Categories.hasMany(models.New, {as: 'news', foreignKey : "categoryId"});
fuera del alcance del ticket.

2022-04-04 01:16 UTC, maxxCeballos commented on models/new.js
> +      New.belongsTo(models.Categories, {as: 'categoriesId', foreignKey : "categoryId"});
Fuera del alcance del ticket

2022-04-04 18:56 UTC, ezequielrango commented on documentation/news.txt
> +https://documenter.getpostman.com/view/17593482/UVsLQRL3
Gracias por el feedback, apenas esté listo el middleware de 'isAdmin' y corregido el del 'jwt' vuelvo a documentar con todos lso tipos de respuesta. El jwt actual me rompe el proyecto.

2022-04-08 14:53 UTC, merged

2022-04-17 00:26 UTC, ezequielrango commented on documentation/news.txt
> +https://documenter.getpostman.com/view/17593482/UVsLQRL3
https://documenter.getpostman.com/view/17593482/UVsLQRL3


![Capture](https://user-images.githubusercontent.com/79542271/163695265-4bea331d-743c-4a48-9ee0-41c72a3865b2.JPG)