Ot 140 62
alkemyTech/OT140-SERVER pull request #96
Opened 2022-03-16 12:18 UTC by jnahuel46

Updated organization public route to show the slides corresponding to each organization.
An association between tables was generated and the Slides model was included in the organization queries.
updated branch
![PRUEBA62](https://user-images.githubusercontent.com/70448601/158588138-6dab024e-d11f-4774-a80c-27e7ea681506.png)

2022-03-18 18:01 UTC, jTomasi-Alkemy requested changes
por favor ver estos comentarios

2022-03-18 18:01 UTC, jTomasi-Alkemy commented on controllers/organization.js
> +
esta linea está de mas

2022-03-18 18:02 UTC, jpromanonet commented on app.js
> +app.use("/organization", organizationsRouter);
Fijate que es organization.js sin S

2022-03-18 18:03 UTC, jpromanonet requested changes
Revisa como estas usando los requires, y fijate de llamar a los archivos correctos.

2022-03-18 18:04 UTC, jpromanonet commented on routes/organizations.js
> -const Organization = require('../models').Organization;
Revisa que la ruta del models no está completa.

2022-03-18 18:05 UTC, jpromanonet requested changes
Revisa como llamas los require en el codigo, pero lo demas esta genial =)

2022-03-22 03:21 UTC, jnahuel46 commented
Cambios Realizados!

2022-04-04 02:38 UTC, maxxCeballos requested changes

2022-04-04 02:38 UTC, maxxCeballos commented on controllers/organization.js
> +};
Esto esta relacionado con ticket 23. Esperar a que se corrija el mismo para hacer los cambios correspondientes en este PR.

2022-04-04 21:55 UTC, jnahuel46 commented
okas!

2022-04-18 19:47 UTC, closed without merging